# Generated by Django 5.0.1 on 2024-02-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='user_name',
        ),
    ]
